image: node:7.4.0

stages:
- install_dependencies
- lint
- test

cache:
  paths:
  - node_modules/

install_dependencies:
  stage: install_dependencies
  script:
    - npm i

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
  - npm test
