image: node:7.4.0
services:
  - redis

before_script:
  - npm install

stages:
- lint
- test

cache:
  paths:
  - node_modules/

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
  - REDIS_URL=redis://redis:6379 npm run test
