global.Promise = require('bluebird')
global.fs = global.Promise.promisifyAll(require('fs'))
require('babel-core/register')
require('dotenv').config()
require('./src/index').default().catch(e => console.trace(e))
